"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env if present.
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str) -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-k1^#+&&&xh=-b(4dxzz)s4-ca=7p&i$2#fyq$jnv0j8dxm=5v^",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

# `.ngrok-free.dev` / `.ngrok-free.app` let you tunnel the app to a phone in dev.
ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,.ngrok-free.dev,.ngrok-free.app",
)

# Render sets this to the service's public hostname — trust it automatically so
# a fresh deploy works before any env vars are customised.
if _render_host := os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # modern admin theme — must come before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'axes',  # admin-login brute-force lockouts
    # Local
    'users',
    'products',
    'messaging',
    'orders',
    'api',
]

# Admin sign-in is the only password login — lock it after repeated failures.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # must be first: enforces lockouts
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5              # failed attempts before lockout
AXES_COOLOFF_TIME = 1               # hours until the lockout lifts
AXES_RESET_ON_SUCCESS = True        # a good login clears the counter
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]  # per attacker+account
AXES_CLIENT_IP_CALLABLE = "api.net.client_ip"  # proxy-aware, same as the API
# The admin form posts the login as "username" even though our USERNAME_FIELD
# is email; without this, axes records attempts under the wrong key and the
# lockout never matches (verified by test).
AXES_USERNAME_FORM_FIELD = "username"

# Custom passwordless user model (email or phone, OTP auth). Must be set before
# the first migration of this project's database.
AUTH_USER_MODEL = 'users.User'

# ── Admin theme (Jazzmin) ────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "Luxeit Admin",
    "site_header": "Luxeit",
    "site_brand": "Luxeit",
    "welcome_sign": "Luxeit Operations",
    "copyright": "Luxeit",
    "search_model": ["orders.Order", "products.Product", "users.User"],
    # Sidebar: related things grouped, ordered for the ops workflow.
    "order_with_respect_to": [
        "orders", "orders.order", "orders.shipment",
        "products", "products.product", "products.category", "products.productreview",
        "users", "messaging",
    ],
    "icons": {
        "orders": "fas fa-clipboard-list",
        "orders.Order": "fas fa-receipt",
        "orders.Shipment": "fas fa-truck-fast",
        "products": "fas fa-store",
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-tags",
        "products.ProductReview": "fas fa-star",
        "users": "fas fa-users",
        "users.User": "fas fa-user",
        "messaging": "fas fa-headset",
        "messaging.Thread": "fas fa-comments",
        "messaging.Message": "fas fa-comment-dots",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # Quick link to the fulfilment board from the top bar + the Orders group.
    "topmenu_links": [
        {"name": "Fulfilment board", "url": "admin:orders_shipment_fulfilment"},
    ],
    "custom_links": {
        "orders": [
            {"name": "Fulfilment board", "url": "admin:orders_shipment_fulfilment", "icon": "fas fa-clipboard-check"},
            {"name": "Analytics", "url": "admin:orders_order_analytics", "icon": "fas fa-chart-line"},
        ],
        "products": [
            {"name": "Review moderation", "url": "admin:products_productreview_moderation", "icon": "far fa-comments"},
        ],
        "messaging": [
            {"name": "Support inbox", "url": "admin:messaging_thread_support_inbox", "icon": "fas fa-headset"},
            {"name": "Send a promotion", "url": "admin:messaging_message_send_promotion", "icon": "fas fa-bullhorn"},
        ],
    },
    "hide_apps": ["auth"],
}
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "default_theme_mode": "auto",  # follows the OS light/dark preference
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-indigo",
    "accent": "accent-indigo",
}

MIDDLEWARE = [
    # First: reject blocklisted IPs before any other work happens.
    'api.middleware.BlockedIPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (admin/Jazzmin CSS) straight from Django —
    # no separate web server needed on Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # last: turns lockouts into 403s
]

# Emergency IP blocklist (comma-separated). Change the env var and restart —
# no deploy needed. See api/middleware.py.
BLOCKED_IPS = set(env_list("DJANGO_BLOCKED_IPS", ""))

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level templates win over app templates — needed to override
        # Jazzmin's admin/base_site.html (Jazzmin is first in INSTALLED_APPS).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.fulfilment_badges',
                'products.context_processors.review_badges',
                'messaging.context_processors.support_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local dev uses SQLite (zero setup). In production set DATABASE_URL to a
# Postgres URL (e.g. from Render/Neon) — SQLite must NOT be used on PaaS hosts,
# whose disks are wiped on every deploy.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,          # persistent connections (ignored by SQLite)
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # `collectstatic` target (deploy builds)

# Uploaded files (product photos). Locally these land in backend/media/ and are
# served by the dev server; in production they go to Cloudflare R2 (see below).
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Cloudflare R2 (S3-compatible) media storage -----------------------------
# Set these env vars to store uploads in R2 instead of the local disk. Leave
# R2_BUCKET empty (the default) and uploads stay on the filesystem, so local dev
# works with zero configuration.
#
#   R2_BUCKET             bucket name, e.g. "luxeit-media"
#   R2_ACCOUNT_ID         Cloudflare account id (used to build the endpoint)
#   R2_ACCESS_KEY_ID      R2 API token access key
#   R2_SECRET_ACCESS_KEY  R2 API token secret
#   R2_PUBLIC_HOST        public host serving the bucket, no scheme —
#                         e.g. "pub-xxxx.r2.dev" or "cdn.luxeit.co.zm"
R2_BUCKET = os.getenv("R2_BUCKET", "")
R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID", "")
R2_PUBLIC_HOST = os.getenv("R2_PUBLIC_HOST", "").replace("https://", "").strip("/")

if R2_BUCKET and R2_ACCOUNT_ID:
    _default_storage = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": R2_BUCKET,
            "endpoint_url": f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
            "access_key": os.getenv("R2_ACCESS_KEY_ID", ""),
            "secret_key": os.getenv("R2_SECRET_ACCESS_KEY", ""),
            "region_name": "auto",
            # R2 rejects S3 ACL headers, and the bucket is served publicly, so
            # don't sign URLs — files get plain, cacheable public URLs.
            "default_acl": None,
            "querystring_auth": False,
            "signature_version": "s3v4",
            "file_overwrite": False,
            "location": "media",
            # Long cache: uploaded files get unique names, so they're immutable.
            "object_parameters": {"CacheControl": "public, max-age=31536000, immutable"},
            **({"custom_domain": R2_PUBLIC_HOST} if R2_PUBLIC_HOST else {}),
        },
    }
else:
    _default_storage = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

# WhiteNoise: hashed filenames + gzip/brotli in production so static assets are
# immutable and cacheable. Plain storage in dev (no manifest to rebuild).
STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": (
            "config.storage.ForgivingManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# True while the test suite runs — used to relax the global throttles so rapid
# test requests don't trip them (per-endpoint scoped throttles stay active).
TESTING = "test" in sys.argv

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Locked down by default — public endpoints opt in with @permission_classes([AllowAny]).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Every API error goes through one gate: technical details to the logs,
    # plain language to the customer (see api/exceptions.py).
    'EXCEPTION_HANDLER': 'api.exceptions.api_exception_handler',
    # Global abuse ceiling: every client gets a per-minute budget (readers and
    # signed-in users separately). Tighter per-action limits below.
    'DEFAULT_THROTTLE_CLASSES': [] if TESTING else [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # How many trusted proxies sit in front of Django (for keying anon limits to
    # the real client IP). 0 in local dev; 1 on Render (its load balancer).
    'NUM_PROXIES': int(os.getenv('DJANGO_NUM_PROXIES', '0')),
    'DEFAULT_THROTTLE_RATES': {
        # Global ceilings (per client). Anon is generous because browser calls
        # arrive via the Next.js proxy and can share an egress IP.
        'anon': os.getenv('DRF_ANON_RATE', '300/min'),
        'user': os.getenv('DRF_USER_RATE', '240/min'),
        # Login codes (most-attacked surface).
        'otp_request': '10/min',      # code requests per IP
        'otp_verify': '20/min',       # verify attempts per IP
        'otp_destination': '5/hour',  # codes sent to a single email/phone
        # Expensive / spammable writes (per signed-in user).
        'orders_create': '30/hour',
        'reviews': '20/hour',
        'support_send': '60/hour',
        'events': '600/hour',  # view/cart tracking — generous, it's cheap
    },
}

# CORS / CSRF — allow the Next.js frontend to call the API with credentials.
# Next dev falls back to :3001 if :3000 is taken, so both are allowed in dev.
CORS_ALLOWED_ORIGINS = env_list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001",
)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,"
    "https://*.ngrok-free.dev,https://*.ngrok-free.app",
)

# Sessions — passwordless login issues a 5-day rolling session cookie.
# The cookie name matches the frontend proxy guard (frontend-ui/src/proxy.ts).
SESSION_COOKIE_NAME = "luxeit_session"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 5  # 5 days
SESSION_SAVE_EVERY_REQUEST = True  # rolling expiry — extend on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS-only in production
CSRF_COOKIE_SECURE = not DEBUG

# OTP delivery — in dev (DEBUG) codes are logged to the console instead of sent.
OTP_DELIVERY_CONSOLE = env_bool("OTP_DELIVERY_CONSOLE", DEBUG)

# Phone/SMS login is disabled until an SMS gateway is paid for and wired up.
# Email login works free. Flip PHONE_LOGIN_ENABLED=True once SMS is ready.
PHONE_LOGIN_ENABLED = env_bool("PHONE_LOGIN_ENABLED", False)

# Google Sign-In: the OAuth *web* client ID from Google Cloud → Google Auth
# Platform → Clients. The backend verifies Google ID tokens against it. Left
# empty, the /api/auth/google endpoint returns 503 (Google sign-in disabled).
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")

# Circuit breaker: total login codes the WHOLE system may send per hour. Even a
# botnet rotating IPs and destinations can't run up the email/SMS bill past
# this. 0 disables the cap. Legit traffic needing more than 500 codes/hour
# means real scale — raise it deliberately, don't remove it.
OTP_GLOBAL_HOURLY_CAP = int(os.getenv("OTP_GLOBAL_HOURLY_CAP", "500"))

# Self-service data export (/api/auth/export). Off for now — data-copy requests
# go through support (Privacy Policy §8). Flip the env var to re-enable.
DATA_EXPORT_ENABLED = env_bool("DATA_EXPORT_ENABLED", False)

# ── Email (login codes + security alerts) ────────────────────────────────────
# Any SMTP provider works. With Resend: host smtp.resend.com, user "resend",
# password = your API key. Unset EMAIL_HOST -> emails print to the console.
if os.getenv("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Luxeit <onboarding@resend.dev>")


# ---------------------------------------------------------------------------
# Production hardening — only applied when DEBUG is off, so local dev (HTTP on
# localhost) is unaffected. Set DJANGO_DEBUG=False in the deployed environment.
# ---------------------------------------------------------------------------
if not DEBUG:
    # Refuse to boot with the throwaway dev key — it would let anyone forge sessions.
    if SECRET_KEY.startswith("django-insecure-"):
        raise RuntimeError("DJANGO_SECRET_KEY must be set to a real secret in production.")

    # Force HTTPS so the session cookie can never travel in plaintext.
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Hardening headers.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

    # When behind a TLS-terminating proxy/load balancer (e.g. Nginx, a PaaS),
    # trust its forwarded-proto header so Django knows the request was HTTPS.
    # Only enable this if such a proxy sets the header — otherwise it's spoofable.
    if env_bool("DJANGO_BEHIND_PROXY", False):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # The browsable API is a dev convenience; serve JSON only in production.
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = ["rest_framework.renderers.JSONRenderer"]
