# Generated by Django 5.2.15 on 2026-06-24 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_category_chips_category_features_category_hero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'In queue'), ('sourcing', 'Sourcing'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('carrier', models.CharField(blank=True, choices=[('air', 'Air'), ('sea', 'Sea')], max_length=4)),
                ('ship_name', models.CharField(blank=True, max_length=150)),
                ('ship_line1', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(blank=True, max_length=120)),
                ('ship_area', models.CharField(blank=True, max_length=120)),
                ('ship_phone', models.CharField(blank=True, max_length=20)),
                ('payment_brand', models.CharField(blank=True, max_length=20)),
                ('payment_detail', models.CharField(blank=True, max_length=40)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=2048)),
                ('warehouse', models.CharField(blank=True, max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-placed_at'], name='orders_orde_placed__c426b5_idx'),
        ),
    ]
