# Generated by Django 5.2.15 on 2026-06-24 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'In queue'), ('sourcing', 'Sourcing'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4c5f76_idx')],
            },
        ),
    ]
