# Generated by Django 5.2.15 on 2026-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('air', 'Air'), ('sea', 'Sea'), ('local', 'Local')], max_length=6),
        ),
    ]
