# Generated by Django 5.2.15 on 2026-06-25 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_shipping_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=10)),
                ('carrier', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea'), ('local', 'Local')], max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'In queue'), ('sourcing', 'Sourcing'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shipment'),
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'In queue'), ('sourcing', 'Sourcing'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.shipment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='OrderEvent',
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', 'created_at'], name='orders_ship_shipmen_2d2035_idx'),
        ),
    ]
