# Generated by Django 5.2.15 on 2026-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shipment_orderitem_shipment_shipmentevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
