# Generated by Django 5.2.15 on 2026-06-25 16:52

from django.db import migrations, models


def backfill_item_status(apps, schema_editor):
    """Existing items inherit their shipment's status (or the order's if the
    item isn't attached to a shipment), so the board reflects current reality."""
    OrderItem = apps.get_model("orders", "OrderItem")
    for item in OrderItem.objects.select_related("shipment", "order").iterator():
        item.status = item.shipment.status if item.shipment_id else item.order.status
        item.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'In queue'), ('sourcing', 'Sourcing'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.RunPython(backfill_item_status, migrations.RunPython.noop),
    ]
