# Generated by Django 5.2.15 on 2026-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'Sourcing'), ('sourcing', 'Sourced'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'Sourcing'), ('sourcing', 'Sourced'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'Sourcing'), ('sourcing', 'Sourced'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('queue', 'Sourcing'), ('sourcing', 'Sourced'), ('transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=12),
        ),
    ]
