# Generated by Django 5.2.15 on 2026-09-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
