# Generated by Django 5.2.15 on 2026-06-16 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('blurb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('footwear', 'Footwear'), ('watch', 'Watch'), ('car_part', 'Car part'), ('security', 'Security'), ('digital', 'Digital'), ('general', 'General')], default='general', max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('media', models.JSONField(blank=True, default=list)),
                ('warehouse', models.CharField(blank=True, choices=[('china', 'China hub'), ('zambia', 'Lusaka (Zambia) hub')], max_length=10)),
                ('origin', models.CharField(blank=True, choices=[('China', 'China'), ('Global', 'Global')], max_length=10)),
                ('shipping_method', models.CharField(blank=True, choices=[('air', 'Air'), ('sea', 'Sea')], max_length=5)),
                ('delivery_estimate', models.CharField(blank=True, max_length=60)),
                ('import_tag', models.CharField(blank=True, max_length=40)),
                ('preorder', models.BooleanField(default=False)),
                ('popularity_label', models.CharField(blank=True, max_length=40)),
                ('searchable_text', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('spec_groups', models.JSONField(blank=True, default=list)),
                ('compatibility', models.JSONField(blank=True, null=True)),
                ('package_contents', models.JSONField(blank=True, default=list)),
                ('notices', models.JSONField(blank=True, default=list)),
                ('review_tags', models.JSONField(blank=True, default=list)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('rating_breakdown', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('avatar_initial', models.CharField(blank=True, max_length=2)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('seller_reply', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sub_category'], name='products_pr_categor_650232_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
    ]
