# Generated by Django 5.2.15 on 2026-06-16 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(help_text='Image URL.', max_length=500)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('object_fit', models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover')], default='contain', max_length=8)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.RemoveField(
            model_name='product',
            name='popularity_label',
        ),
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(default=0, help_text="Total units sold (drives the 'X sold' label)."),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, help_text='Optional product video URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='video_thumbnail',
            field=models.CharField(blank=True, help_text='Poster image for the video.', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(help_text='Main thumbnail image (required).', max_length=500, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['warehouse'], name='products_pr_warehou_6b4548_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-units_sold'], name='products_pr_units_s_1a02c0_idx'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
