# Generated by Django 5.2.15 on 2026-06-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_remove_product_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='seller_reply',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full description shown on the product detail page.'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reply_author',
            field=models.CharField(blank=True, default='LUXEIT Support', max_length=120),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reply_text',
            field=models.TextField(blank=True),
        ),
    ]
