# Generated by Django 5.2.15 on 2026-06-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productreview_seller_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='hero',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='search_placeholder',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(help_text='Main thumbnail image (required).', max_length=2048, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.CharField(help_text='Image URL or data URI.', max_length=2048),
        ),
    ]
