# Generated by Django 5.2.15 on 2026-06-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_chips_category_features_category_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
