# Generated by Django 5.2.15 on 2026-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='air_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='China hub only: price when shipped by air. Leave blank if only sea shipping is offered.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Sea/standard price (China hub) or the local price (Zambia hub).', max_digits=10),
        ),
    ]
