# Generated by Django 5.2.15 on 2026-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productevent_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail photo. If set, this is used instead of the thumbnail URL above.', upload_to='products/', verbose_name='thumbnail upload'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload a photo. If set, this is used instead of the URL above.', upload_to='products/gallery/', verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.CharField(blank=True, help_text='Image URL or data URI.', max_length=2048),
        ),
    ]
