# Generated by Django 5.2.15 on 2026-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image_file_productimage_src_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Image URL or data URI. Leave blank if you upload a thumbnail below.', max_length=2048, verbose_name='thumbnail URL'),
        ),
    ]
