# Generated by Django 5.2.15 on 2026-08-13 08:06

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail photo. If set, this is used instead of the thumbnail URL above.', upload_to='products/', validators=[products.validators.validate_product_image], verbose_name='thumbnail upload'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload a photo. If set, this is used instead of the URL above.', upload_to='products/gallery/', validators=[products.validators.validate_product_image], verbose_name='upload'),
        ),
    ]
