# Generated by Django 5.2.15 on 2026-08-19 14:19

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image_file_alter_productimage_src_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='src',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail photo.', upload_to='products/', validators=[products.validators.validate_product_image], verbose_name='thumbnail upload'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload a photo.', upload_to='products/gallery/', validators=[products.validators.validate_product_image], verbose_name='upload'),
        ),
    ]
