import { type CategoryConfig, makeListingImage } from "@/lib/category/shared";

export const electronicsConfig: CategoryConfig = {
  slug: "electronics",
  title: "Electronics",
  subtitle: "Phones, laptops, audio, TVs, and smart gadgets",
  searchPlaceholder: "Search electronics...",
  hero: {
    badge: "Top Tech",
    title: "Latest Electronics",
    subtitle: "Genuine gadgets from trusted suppliers",
  },
  chips: [
    { key: "all", label: "All", icon: "Sparkles" },
    { key: "phones", label: "Phones", icon: "Smartphone" },
    { key: "laptops", label: "Laptops", icon: "Laptop" },
    { key: "audio", label: "Audio", icon: "Headphones" },
    { key: "tvs", label: "TVs", icon: "Tv" },
    { key: "gaming", label: "Gaming", icon: "Gamepad2" },
    { key: "wearables", label: "Wearables", icon: "Watch" },
    { key: "cameras", label: "Cameras", icon: "Camera" },
  ],
  features: [
    { icon: "ShieldCheck", title: "Genuine Products", subtitle: "Authentic & warrantied", tint: "text-emerald-500", ring: "bg-emerald-500/10" },
    { icon: "Truck", title: "Fast Shipping", subtitle: "Worldwide delivery", tint: "text-sky-500", ring: "bg-sky-500/10" },
    { icon: "RotateCcw", title: "Easy Returns", subtitle: "Hassle-free returns", tint: "text-violet-500", ring: "bg-violet-500/10" },
  ],
  products: [
    { id: "el-pulse-x5", slug: "pulse-x5-smartphone", title: "Pulse X5 Smartphone", subtitle: "6.7\" 5G · 256GB", subCategory: "phones", price: 329.99, originalPrice: 379.99, badge: { label: "-13%", tone: "sale" }, image: makeListingImage("PHONE", "#1e1b4b", "#4338ca") },
    { id: "el-nova-lite", slug: "nova-lite-smartphone", title: "Nova Lite Smartphone", subtitle: "Budget 4G · 128GB", subCategory: "phones", price: 149.99, image: makeListingImage("NOVA", "#0c4a6e", "#0ea5e9") },
    { id: "el-zenbook-air", slug: "zenbook-air-laptop", title: "ZenBook Air Laptop", subtitle: "14\" · 16GB · 512GB SSD", subCategory: "laptops", price: 749.99, originalPrice: 829.99, badge: { label: "-10%", tone: "sale" }, image: makeListingImage("LAPTOP", "#0a0a0a", "#3f3f46") },
    { id: "el-titan-gaming", slug: "titan-gaming-laptop", title: "Titan Gaming Laptop", subtitle: "15.6\" · RTX · 1TB SSD", subCategory: "laptops", price: 1199.99, badge: { label: "NEW", tone: "new" }, image: makeListingImage("GAMING", "#3b0764", "#a855f7") },
    { id: "el-airbeat-buds", slug: "airbeat-wireless-earbuds", title: "AirBeat Wireless Earbuds", subtitle: "ANC · 30h battery", subCategory: "audio", price: 39.99, originalPrice: 59.99, badge: { label: "-33%", tone: "sale" }, image: makeListingImage("EARBUDS", "#134e4a", "#14b8a6") },
    { id: "el-studio-over-ear", slug: "studio-over-ear-headphones", title: "Studio Over-Ear Headphones", subtitle: "Wireless · Hi-Res", subCategory: "audio", price: 89.99, image: makeListingImage("HEADPHONES", "#4c0519", "#e11d48") },
    { id: "el-boom-speaker", slug: "boom-portable-speaker", title: "Boom Portable Speaker", subtitle: "Bluetooth · Waterproof", subCategory: "audio", price: 49.99, image: makeListingImage("SPEAKER", "#155e75", "#22d3ee") },
    { id: "el-vivid-43-tv", slug: "vivid-43-4k-smart-tv", title: "Vivid 43\" 4K Smart TV", subtitle: "HDR · Streaming built-in", subCategory: "tvs", price: 299.99, originalPrice: 359.99, badge: { label: "-17%", tone: "sale" }, image: makeListingImage("4K TV", "#172554", "#2563eb") },
    { id: "el-cinema-55-tv", slug: "cinema-55-qled-tv", title: "Cinema 55\" QLED TV", subtitle: "QLED · 120Hz", subCategory: "tvs", price: 549.99, badge: { label: "NEW", tone: "new" }, image: makeListingImage("QLED", "#0a0a0a", "#1d4ed8") },
    { id: "el-nexus-console", slug: "nexus-game-console", title: "Nexus Game Console", subtitle: "4K Gaming · 1TB", subCategory: "gaming", price: 449.99, image: makeListingImage("CONSOLE", "#1e1b4b", "#6d28d9") },
    { id: "el-pro-controller", slug: "pro-wireless-controller", title: "Pro Wireless Controller", subtitle: "Low-latency · Rechargeable", subCategory: "gaming", price: 54.99, originalPrice: 69.99, badge: { label: "-21%", tone: "sale" }, image: makeListingImage("PAD", "#3b0764", "#9333ea") },
    { id: "el-pulse-watch", slug: "pulse-smartwatch", title: "Pulse Smartwatch", subtitle: "AMOLED · Heart-rate · GPS", subCategory: "wearables", price: 119.99, originalPrice: 149.99, badge: { label: "-20%", tone: "sale" }, image: makeListingImage("WATCH", "#0f172a", "#0ea5e9") },
    { id: "el-fit-band", slug: "fit-tracker-band", title: "Fit Tracker Band", subtitle: "Sleep & activity tracking", subCategory: "wearables", price: 34.99, image: makeListingImage("BAND", "#134e4a", "#10b981") },
    { id: "el-action-cam", slug: "action-4k-camera", title: "Action 4K Camera", subtitle: "Waterproof · Stabilized", subCategory: "cameras", price: 129.99, originalPrice: 159.99, badge: { label: "-19%", tone: "sale" }, image: makeListingImage("ACTION", "#1c1917", "#f59e0b") },
    { id: "el-mirrorless-cam", slug: "mirrorless-camera-kit", title: "Mirrorless Camera Kit", subtitle: "24MP · 18-55mm lens", subCategory: "cameras", price: 529.99, badge: { label: "NEW", tone: "new" }, image: makeListingImage("CAMERA", "#0a0a0a", "#52525b") },
  ],
};
