import type { Product } from "@/types/product";

const BASE_REVIEW_TAGS = [
  { label: "Price Consistency", count: 612 },
  { label: "Product Quality", count: 422 },
  { label: "Fast Delivery", count: 288 },
  { label: "Accurate Description", count: 241 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-sec-cam-1",
    slug: "smart-cctv-4k-hub-kit",
    warehouse: "china",
    title: "Smart CCTV 4K Hub Kit",
    image: "/images/mock-products/security-kit.svg",
    productType: "security",
    media: [
      {
        type: "image",
        src: "/images/mock-products/security-kit.svg",
        alt: "Smart CCTV 4K Hub Kit main image",
        objectFit: "contain",
      },
      {
        type: "image",
        src: "/images/mock-products/security-kit.svg",
        alt: "Smart CCTV 4K Hub Kit specifications image",
        objectFit: "contain",
      },
      {
        type: "video",
        src: "/videos/products/security-kit-demo.mp4",
        thumbnail: "/images/mock-products/security-kit.svg",
        title: "Smart CCTV 4K Hub Kit demo video",
      },
    ],
    price: 129.0,
    preorder: true,
    importTag: "Import",
    origin: "China",
    deliveryEstimate: "5-10 days",
    shippingMethod: "air",
    category: "Security",
    popularityLabel: "41.2k",
    searchableText: "security cctv camera monitor dvr hub",
    specGroups: [
      {
        title: "Security Specifications",
        specs: [
          { label: "Resolution", value: "4K UHD" },
          { label: "Camera Count", value: "4 Cameras" },
          { label: "Night Vision", value: "Up to 25m" },
          { label: "Storage", value: "1TB DVR Included" },
          { label: "App Support", value: "iOS / Android" },
          { label: "Power Type", value: "Wired + Adapter" },
        ],
      },
    ],
    packageContents: [
      "4x CCTV Cameras",
      "1x DVR Unit",
      "Power Adapter Set",
      "Mounting Screws + Cable",
    ],
    notices: ["Installation service available on request."],
    ratings: {
      ratingAverage: 4.4,
      ratingCount: 2974134,
      ratingBreakdown: {
        5: 1981120,
        4: 612435,
        3: 241553,
        2: 93244,
        1: 45882,
      },
      reviewTags: BASE_REVIEW_TAGS,
      reviews: [
        {
          id: "sec-r-1",
          userName: "Kristin Lynch",
          avatarInitial: "K",
          rating: 5,
          date: "2026-05-18",
          text: "Very clear night vision and easy setup. We installed it at our store and the app pairing was quick.",
          helpfulCount: 1,
        },
        {
          id: "sec-r-2",
          userName: "Ravi Kant Bhargava",
          avatarInitial: "R",
          rating: 1,
          date: "2026-04-25",
          text: "Had issues with my first DVR unit but support helped me replace it. Setup instructions can be clearer.",
          helpfulCount: 6,
          sellerReply: {
            author: "LUXEIT Support",
            date: "2026-04-29",
            text: "Sorry about the issue. We have shared a step-by-step setup guide and replacement support in your inbox.",
          },
        },
        {
          id: "sec-r-3",
          userName: "Jay",
          avatarInitial: "J",
          rating: 4,
          date: "2026-05-06",
          text: "Good quality cameras for the price. Delivery took slightly longer than expected but still worth it.",
          helpfulCount: 4,
        },
      ],
    },
  },
  {
    id: "prod-gaming-1",
    slug: "ps5-cooling-dock-pro",
    warehouse: "china",
    title: "PS5 Cooling Dock Pro",
    image: "/images/mock-products/ps5-dock.svg",
    productType: "digital",
    media: [
      {
        type: "image",
        src: "/images/mock-products/ps5-dock.svg",
        alt: "PS5 Cooling Dock Pro main image",
        objectFit: "contain",
      },
      {
        type: "image",
        src: "/images/mock-products/ps5-dock.svg",
        alt: "PS5 Cooling Dock Pro details image",
        objectFit: "contain",
      },
    ],
    price: 32.5,
    importTag: "Import",
    origin: "China",
    deliveryEstimate: "7-14 days",
    shippingMethod: "sea",
    category: "Gaming",
    popularityLabel: "19.8k",
    searchableText: "ps5 cooling stand gaming console accessories",
    specGroups: [
      {
        title: "Delivery",
        specs: [
          { label: "Region", value: "Global" },
          { label: "Delivery Type", value: "Instant digital message" },
          { label: "Delivery Estimate", value: "Within 15 minutes" },
        ],
      },
    ],
    notices: ["Redemption instructions are provided after payment confirmation."],
    ratings: {
      ratingAverage: 4.2,
      ratingCount: 18342,
      ratingBreakdown: {
        5: 10221,
        4: 4802,
        3: 2014,
        2: 852,
        1: 453,
      },
      reviewTags: [
        { label: "Cooling Performance", count: 248 },
        { label: "Build Quality", count: 196 },
        { label: "Fast Delivery", count: 143 },
      ],
      reviews: [
        {
          id: "ps5-r-1",
          userName: "M. Banda",
          avatarInitial: "M",
          rating: 5,
          date: "2026-05-11",
          text: "Works perfectly with my PS5 setup. Quiet fan and clean cable management.",
          helpfulCount: 8,
        },
        {
          id: "ps5-r-2",
          userName: "T. Chola",
          avatarInitial: "T",
          rating: 4,
          date: "2026-05-03",
          text: "Solid dock for the price. Packaging was good and arrived in one piece.",
          helpfulCount: 3,
        },
      ],
    },
  },
  {
    id: "prod-pc-1",
    slug: "rgb-gaming-mousepad-xl",
    warehouse: "zambia",
    title: "RGB Gaming Mousepad XL",
    image: "/images/mock-products/mousepad.svg",
    productType: "watch",
    media: [
      {
        type: "image",
        src: "/images/mock-products/mousepad.svg",
        alt: "RGB Gaming Mousepad XL main image",
        objectFit: "contain",
      },
      {
        type: "image",
        src: "/images/mock-products/mousepad.svg",
        alt: "RGB Gaming Mousepad XL dimension image",
        objectFit: "contain",
      },
    ],
    price: 14.99,
    origin: "Global",
    deliveryEstimate: "4-8 days",
    shippingMethod: "air",
    category: "PC",
    popularityLabel: "67.5k",
    searchableText: "pc rgb mousepad gaming desk mat",
    options: [
      {
        name: "Strap Color",
        key: "strap_color",
        required: false,
        values: ["Black", "Midnight Blue", "Silver"],
      },
    ],
    specGroups: [
      {
        title: "Watch Specifications",
        specs: [
          { label: "Water Resistance", value: "30m" },
          { label: "Movement", value: "Quartz" },
          { label: "Case Size", value: "42mm" },
          { label: "Strap Material", value: "Silicone" },
          { label: "Battery Type", value: "CR2032" },
          { label: "Display Type", value: "AMOLED" },
        ],
      },
    ],
    notices: ["Imported item includes 6-month seller warranty."],
    ratings: {
      ratingAverage: 4.1,
      ratingCount: 9621,
      ratingBreakdown: {
        5: 5010,
        4: 2711,
        3: 1205,
        2: 451,
        1: 244,
      },
      reviewTags: [
        { label: "Value for Money", count: 191 },
        { label: "Design", count: 133 },
      ],
      reviews: [
        {
          id: "pc-r-1",
          userName: "Chisomo",
          avatarInitial: "C",
          rating: 4,
          date: "2026-05-09",
          text: "Nice desk setup upgrade. RGB is bright and surface is smooth.",
          helpfulCount: 2,
        },
      ],
    },
  },
  {
    id: "prod-auto-1",
    slug: "led-headlight-dual-pack",
    warehouse: "zambia",
    title: "LED Headlight Dual Pack",
    image: "/images/mock-products/headlight.svg",
    productType: "car_part",
    price: 48.0,
    importTag: "Import",
    origin: "China",
    deliveryEstimate: "6-12 days",
    shippingMethod: "sea",
    category: "Auto",
    popularityLabel: "9.4k",
    searchableText: "car parts led headlight auto accessories",
    compatibility: {
      title: "Vehicle Compatibility",
      required: true,
      fields: [
        {
          key: "vehicle",
          label: "Select vehicle",
          required: true,
          values: ["Toyota Corolla 2014-2018", "Honda Fit 2015-2020", "Nissan Note 2016-2021"],
        },
        {
          key: "position",
          label: "Part position",
          required: true,
          values: ["Front Left", "Front Right"],
        },
      ],
      note: "Confirm compatibility before order.",
    },
    specGroups: [
      {
        title: "Electrical Specs",
        specs: [
          { label: "Voltage", value: "12V" },
          { label: "Socket", value: "H11" },
          { label: "Color Temp", value: "6500K" },
        ],
      },
    ],
    notices: ["Installation by qualified technician recommended."],
    ratings: {
      ratingAverage: 4.0,
      ratingCount: 7044,
      ratingBreakdown: {
        5: 3320,
        4: 2201,
        3: 915,
        2: 404,
        1: 204,
      },
      reviewTags: [
        { label: "Brightness", count: 96 },
        { label: "Fitment", count: 88 },
      ],
      reviews: [
        {
          id: "auto-r-1",
          userName: "P. Zulu",
          avatarInitial: "P",
          rating: 4,
          date: "2026-05-01",
          text: "Good brightness and clean beam pattern. Check your socket type before ordering.",
          helpfulCount: 5,
        },
      ],
    },
  },
  {
    id: "prod-life-1",
    slug: "minimal-leather-sling-bag",
    warehouse: "zambia",
    title: "Minimal Leather Sling Bag",
    image: "/images/mock-products/sling-bag.svg",
    productType: "footwear",
    price: 22.0,
    preorder: true,
    origin: "Global",
    deliveryEstimate: "5-9 days",
    shippingMethod: "air",
    category: "Lifestyle",
    popularityLabel: "28.1k",
    searchableText: "fashion sling bag lifestyle premium",
    options: [
      {
        name: "Size",
        key: "size",
        required: true,
        values: ["36", "37", "38", "39", "40", "41", "42"],
        stockByValue: {
          "36": 6,
          "37": 4,
          "38": 8,
          "39": 5,
          "40": 7,
          "41": 3,
          "42": 2,
        },
      },
      {
        name: "Color",
        key: "color",
        required: false,
        values: ["Black", "Brown", "Cream"],
      },
    ],
    specGroups: [
      {
        title: "Material & Fit",
        specs: [
          { label: "Upper", value: "Premium synthetic leather" },
          { label: "Sole", value: "Rubber grip sole" },
          { label: "Fit", value: "True to size" },
        ],
      },
    ],
    notices: ["Size guide: choose your normal size for the best fit."],
    ratings: {
      ratingAverage: 4.3,
      ratingCount: 11382,
      ratingBreakdown: {
        5: 6402,
        4: 3044,
        3: 1296,
        2: 441,
        1: 199,
      },
      reviewTags: [
        { label: "Comfort", count: 222 },
        { label: "Material", count: 178 },
      ],
      reviews: [
        {
          id: "life-r-1",
          userName: "L. Mwansa",
          avatarInitial: "L",
          rating: 5,
          date: "2026-05-14",
          text: "Stylish and comfortable for daily use. Fits true to size.",
          helpfulCount: 7,
        },
      ],
    },
  },
  {
    id: "prod-beauty-1",
    slug: "skin-care-mini-device-kit",
    warehouse: "china",
    title: "Skin Care Mini Device Kit",
    image: "/images/mock-products/skin-care.svg",
    productType: "general",
    price: 26.75,
    importTag: "Import",
    origin: "China",
    deliveryEstimate: "7-13 days",
    shippingMethod: "sea",
    category: "Beauty",
    popularityLabel: "12.6k",
    searchableText: "beauty skin care wellness device",
    ratings: {
      ratingAverage: 4.0,
      ratingCount: 3012,
      ratingBreakdown: {
        5: 1501,
        4: 983,
        3: 342,
        2: 129,
        1: 57,
      },
      reviewTags: [
        { label: "Packaging", count: 62 },
        { label: "Results", count: 54 },
      ],
      reviews: [
        {
          id: "beauty-r-1",
          userName: "N. Phiri",
          avatarInitial: "N",
          rating: 4,
          date: "2026-05-02",
          text: "Compact kit and simple to use at home.",
          helpfulCount: 1,
        },
      ],
    },
  },
];

export const POPULAR_SEARCH_TERMS = [
  "CCTV Camera",
  "PS5 Stand",
  "RGB Mousepad",
  "Car LED Lights",
  "Leather Bag",
];

export const RECENT_SEARCH_TERMS = [
  "Gaming accessories",
  "Security monitor",
  "Import car parts",
];
