"""Extra demo stock for the seeder.

Kept out of seed_products.py so the command stays readable. Each product tuple
is (sub_category, name, subtitle, sea_price, warehouse, original_price|None).

This is demo data for testing — it is deleted and recreated on every seed.
"""

from products.models import ProductType

# Deepens the categories that already exist in seed_products.CATEGORIES.
EXTRA_PRODUCTS = {
    "footwear": [
        ("sneakers", "CloudStep Knit Runners", "Breathable knit trainers", 54.99, "china", 64.99),
        ("sneakers", "Retro Court Trainers", "Classic court silhouette", 47.99, "china", None),
        ("sneakers", "TrailGrip Off-Road Shoes", "Rugged outdoor sneakers", 66.99, "china", 79.99),
        ("sneakers", "SlipOn Comfort Loafers", "Easy everyday slip-ons", 39.99, "china", None),
        ("boots", "Desert Suede Boots", "Chukka-style ankle boots", 74.99, "china", 89.99),
        ("boots", "SteelToe Work Boots", "Safety boots for site work", 89.99, "zambia", None),
        ("boots", "Winter Lined Boots", "Fleece-lined high tops", 82.99, "china", None),
        ("sandals", "Aqua Slide Sandals", "Pool and beach slides", 19.99, "china", 24.99),
        ("sandals", "Leather Strap Sandals", "Handmade leather sandals", 34.99, "zambia", None),
        ("formal", "Oxford Dress Shoes", "Polished leather oxfords", 79.99, "china", 94.99),
        ("formal", "Derby Lace-Ups", "Smart office footwear", 69.99, "china", None),
        ("formal", "Suede Loafers", "Soft suede slip-on", 64.99, "china", None),
        ("sports", "Court Basketball Shoes", "High-top ankle support", 84.99, "china", 99.99),
        ("sports", "Astro Turf Boots", "Grip soles for turf", 57.99, "china", None),
    ],
    "watches": [
        ("luxury", "Chrono Gold Automatic", "Gold-tone automatic chronograph", 189.99, "china", 229.99),
        ("luxury", "Skeleton Dial Mechanical", "Exposed movement dress watch", 164.99, "china", None),
        ("luxury", "Rose Gold Slim Dress", "Minimal slim profile", 129.99, "china", 154.99),
        ("luxury", "Moonphase Classic", "Moonphase complication", 214.99, "china", None),
        ("smart", "FitPulse Smart Watch", "Heart rate and step tracking", 74.99, "china", 89.99),
        ("smart", "AMOLED Sport Watch", "Bright always-on display", 94.99, "china", None),
        ("smart", "Rugged GPS Watch", "Outdoor GPS and altimeter", 119.99, "china", 139.99),
        ("smart", "Kids Tracker Watch", "Call and locate your child", 49.99, "china", None),
        ("casual", "Canvas Strap Field Watch", "Everyday military style", 44.99, "china", None),
        ("casual", "Diver 200m Steel", "Rotating bezel dive watch", 109.99, "china", 129.99),
        ("casual", "Minimalist Mesh Band", "Slim mesh bracelet", 54.99, "china", None),
        ("casual", "Dual-Time Traveller", "Track two time zones", 79.99, "china", None),
        ("ladies", "Ladies Ceramic White", "Ceramic link bracelet", 124.99, "china", 149.99),
        ("ladies", "Crystal Bezel Watch", "Stone-set bezel", 89.99, "china", None),
        ("ladies", "Petite Leather Watch", "Slim 28mm case", 64.99, "china", None),
        ("ladies", "Bangle Cuff Watch", "Jewellery-style cuff", 74.99, "china", 89.99),
    ],
    "electronics": [
        ("audio", "ANC Over-Ear Headphones", "Active noise cancelling", 89.99, "china", 109.99),
        ("audio", "TWS Earbuds Pro", "Wireless earbuds with case", 39.99, "china", 49.99),
        ("audio", "Party Bluetooth Speaker", "Loud outdoor speaker", 79.99, "china", None),
        ("audio", "Soundbar 2.1 Home", "TV soundbar with subwoofer", 129.99, "china", 159.99),
        ("mobile", "20000mAh Power Bank", "Fast-charge power bank", 34.99, "china", 44.99),
        ("mobile", "65W GaN Charger", "Compact multi-port charger", 29.99, "china", None),
        ("mobile", "Magnetic Car Mount", "Dashboard phone holder", 17.99, "china", None),
        ("mobile", "Selfie Ring Light Tripod", "Content creator kit", 24.99, "china", 32.99),
        ("computing", "Wireless Keyboard & Mouse", "Slim desktop combo", 44.99, "china", None),
        ("computing", "USB-C 8-in-1 Hub", "HDMI, SD and ethernet", 39.99, "china", 49.99),
        ("computing", "1080p Streaming Webcam", "Auto-focus webcam", 34.99, "china", None),
        ("computing", "Portable SSD 1TB", "Pocket external drive", 89.99, "china", 109.99),
        ("home", "Robot Vacuum Cleaner", "App-controlled cleaning", 199.99, "china", 249.99),
        ("home", "Air Fryer 5L Digital", "Oil-free cooking", 84.99, "zambia", None),
    ],
    "security": [
        ("cameras", "4K Dome CCTV Camera", "Indoor dome camera", 74.99, "china", 89.99),
        ("cameras", "PTZ Outdoor Camera", "Pan, tilt and zoom", 129.99, "china", None),
        ("cameras", "Solar Wireless Camera", "Solar powered, no wiring", 109.99, "china", 134.99),
        ("cameras", "Dashcam Front & Rear", "Dual-channel dash camera", 64.99, "china", None),
        ("alarms", "Wireless Alarm Kit", "Siren, sensors and remote", 94.99, "china", None),
        ("alarms", "Smart Door Sensor Pack", "Four-door contact set", 34.99, "china", 44.99),
        ("alarms", "Panic Button Remote", "One-touch emergency alert", 22.99, "zambia", None),
        ("access", "Fingerprint Door Lock", "Biometric smart lock", 149.99, "china", 179.99),
        ("access", "Video Doorbell 2K", "See visitors on your phone", 89.99, "china", None),
        ("access", "RFID Access Keypad", "Card and PIN entry", 69.99, "china", None),
        ("access", "Electric Gate Motor", "Sliding gate automation", 269.99, "zambia", 319.99),
        ("access", "Intercom Video Kit", "Two-way door intercom", 119.99, "china", None),
    ],
}


# Accessory-led categories, matching the LUXE iT Accessories brand.
NEW_CATEGORIES = [
    {
        "slug": "watch-cases", "name": "Watch Cases", "type": ProductType.GENERAL,
        "subtitle": "Storage, winders and travel cases for your collection",
        "search": "Search watch cases...",
        "hero": {"badge": "Collector's Choice", "title": "Keep It Pristine",
                 "subtitle": "Cases and winders built to protect"},
        "chips": [
            {"key": "all", "label": "All", "icon": "Sparkles"},
            {"key": "boxes", "label": "Storage Boxes", "icon": "Package"},
            {"key": "winders", "label": "Winders", "icon": "RotateCcw"},
            {"key": "travel", "label": "Travel", "icon": "Briefcase"},
        ],
        "products": [
            ("boxes", "12-Slot Leather Watch Box", "Glass-top display case", 64.99, "china", 79.99),
            ("boxes", "6-Slot Carbon Watch Case", "Carbon-fibre finish", 44.99, "china", None),
            ("boxes", "24-Slot Collector Cabinet", "Two-tier storage cabinet", 119.99, "china", 149.99),
            ("boxes", "Wooden Walnut Watch Box", "Solid walnut with velvet", 89.99, "china", None),
            ("winders", "Single Automatic Winder", "Silent motor winder", 79.99, "china", 94.99),
            ("winders", "Dual Watch Winder", "Winds two automatics", 129.99, "china", None),
            ("winders", "Quad Winder Cabinet", "Four-watch rotating cabinet", 219.99, "china", 269.99),
            ("travel", "Zip Travel Watch Roll", "Three-watch leather roll", 34.99, "china", None),
            ("travel", "Hard Shell Watch Case", "Crush-proof travel case", 49.99, "china", 59.99),
            ("travel", "Single Watch Pouch", "Soft microfibre pouch", 14.99, "zambia", None),
            ("travel", "Watch Strap Tool Kit", "Pin removal and spring bars", 19.99, "china", None),
            ("travel", "Microfibre Polish Cloth Set", "Scratch-safe cleaning set", 9.99, "zambia", None),
        ],
    },
    {
        "slug": "accessories", "name": "Accessories", "type": ProductType.GENERAL,
        "subtitle": "Belts, wallets, sunglasses and everyday carry",
        "search": "Search accessories...",
        "hero": {"badge": "Finishing Touches", "title": "Details That Define",
                 "subtitle": "The pieces that complete the look"},
        "chips": [
            {"key": "all", "label": "All", "icon": "Sparkles"},
            {"key": "eyewear", "label": "Sunglasses", "icon": "Sun"},
            {"key": "wallets", "label": "Wallets", "icon": "CreditCard"},
            {"key": "belts", "label": "Belts", "icon": "Minus"},
            {"key": "grooming", "label": "Grooming", "icon": "Scissors"},
        ],
        "products": [
            ("eyewear", "Aviator Polarised Sunglasses", "Gold frame, UV400 lenses", 39.99, "china", 49.99),
            ("eyewear", "Matte Black Wayfarers", "Everyday polarised classic", 29.99, "china", None),
            ("eyewear", "Rimless Gold Sunglasses", "Lightweight rimless frame", 44.99, "china", 54.99),
            ("eyewear", "Sport Wrap Sunglasses", "Secure fit for running", 34.99, "china", None),
            ("eyewear", "Blue-Light Reading Glasses", "Screen comfort lenses", 19.99, "china", None),
            ("wallets", "RFID Leather Bifold", "Blocks card skimming", 24.99, "china", 32.99),
            ("wallets", "Slim Card Holder", "Six-card minimal holder", 16.99, "china", None),
            ("wallets", "Zip-Around Travel Wallet", "Passport and cards", 34.99, "china", None),
            ("wallets", "Money Clip Wallet", "Steel clip, leather body", 21.99, "china", 27.99),
            ("belts", "Reversible Dress Belt", "Black one side, brown the other", 27.99, "china", None),
            ("belts", "Automatic Ratchet Belt", "Micro-adjust buckle", 32.99, "china", 39.99),
            ("belts", "Woven Casual Belt", "Stretch woven weave", 22.99, "china", None),
            ("belts", "Gold Buckle Leather Belt", "Statement gold buckle", 39.99, "china", 49.99),
            ("grooming", "Beard Trimmer Kit", "Cordless with guards", 44.99, "china", 54.99),
            ("grooming", "Manicure Grooming Set", "Stainless 12-piece set", 24.99, "china", None),
            ("grooming", "Electric Nose Trimmer", "Washable rotary head", 17.99, "china", None),
            ("grooming", "Luxury Fragrance Gift Set", "Three-bottle collection", 59.99, "china", 74.99),
            ("grooming", "Cufflink & Tie Clip Set", "Boxed gift set", 29.99, "china", None),
        ],
    },
    {
        "slug": "bags", "name": "Bags & Luggage", "type": ProductType.GENERAL,
        "subtitle": "Backpacks, travel luggage and everyday carry",
        "search": "Search bags...",
        "hero": {"badge": "Travel Ready", "title": "Carry It Well", "subtitle": "Built for the journey"},
        "chips": [
            {"key": "all", "label": "All", "icon": "Sparkles"},
            {"key": "backpacks", "label": "Backpacks", "icon": "Backpack"},
            {"key": "luggage", "label": "Luggage", "icon": "Luggage"},
            {"key": "handbags", "label": "Handbags", "icon": "ShoppingBag"},
        ],
        "products": [
            ("backpacks", "Anti-Theft Laptop Backpack", "Hidden zips, USB port", 49.99, "china", 62.99),
            ("backpacks", "Water-Resistant Hiking Pack", "35L outdoor pack", 59.99, "china", None),
            ("backpacks", "Slim Business Backpack", "Fits a 15-inch laptop", 44.99, "china", None),
            ("backpacks", "Canvas Vintage Rucksack", "Leather-trim canvas", 39.99, "china", 49.99),
            ("luggage", "Hard Shell Cabin Case", "Spinner wheels, TSA lock", 89.99, "china", 109.99),
            ("luggage", "Large Check-In Trolley", "78cm expandable case", 129.99, "china", None),
            ("luggage", "3-Piece Luggage Set", "Cabin, medium and large", 219.99, "china", 269.99),
            ("luggage", "Duffel Weekender Bag", "Cabin-friendly duffel", 44.99, "china", None),
            ("handbags", "Quilted Shoulder Bag", "Chain strap handbag", 54.99, "china", 69.99),
            ("handbags", "Leather Tote Bag", "Everyday work tote", 64.99, "china", None),
            ("handbags", "Crossbody Sling Bag", "Compact daily sling", 27.99, "china", None),
            ("handbags", "Evening Clutch Purse", "Gold-clasp clutch", 34.99, "china", 44.99),
        ],
    },
    {
        "slug": "jewellery", "name": "Jewellery", "type": ProductType.GENERAL,
        "subtitle": "Chains, rings, bracelets and gift sets",
        "search": "Search jewellery...",
        "hero": {"badge": "Statement Pieces", "title": "Wear The Shine",
                 "subtitle": "Gold-tone and stainless steel"},
        "chips": [
            {"key": "all", "label": "All", "icon": "Sparkles"},
            {"key": "chains", "label": "Chains", "icon": "Link"},
            {"key": "bracelets", "label": "Bracelets", "icon": "Circle"},
            {"key": "rings", "label": "Rings", "icon": "CircleDot"},
            {"key": "sets", "label": "Gift Sets", "icon": "Gift"},
        ],
        "products": [
            ("chains", "Gold Cuban Link Chain", "18k gold-plated steel", 49.99, "china", 64.99),
            ("chains", "Rope Chain Necklace", "Twisted rope design", 39.99, "china", None),
            ("chains", "Figaro Chain 5mm", "Classic figaro links", 34.99, "china", None),
            ("chains", "Pendant Cross Necklace", "Gold-tone cross pendant", 29.99, "china", 37.99),
            ("bracelets", "Gold Cuban Bracelet", "Matches the Cuban chain", 32.99, "china", None),
            ("bracelets", "Beaded Stone Bracelet", "Natural stone beads", 19.99, "china", None),
            ("bracelets", "Steel Bangle Cuff", "Polished open cuff", 24.99, "china", 31.99),
            ("bracelets", "Leather Wrap Bracelet", "Braided leather wrap", 17.99, "china", None),
            ("rings", "Signet Gold Ring", "Engravable flat face", 27.99, "china", None),
            ("rings", "Stainless Band Ring", "Brushed steel band", 19.99, "china", None),
            ("rings", "Stone-Set Statement Ring", "Cubic zirconia setting", 34.99, "china", 44.99),
            ("sets", "Chain & Bracelet Gift Set", "Matching two-piece set", 69.99, "china", 89.99),
            ("sets", "Ladies Jewellery Gift Box", "Necklace, earrings, bracelet", 59.99, "china", 74.99),
            ("sets", "Couples Bracelet Pair", "His and hers set", 39.99, "china", None),
        ],
    },
    {
        "slug": "home-living", "name": "Home & Living", "type": ProductType.GENERAL,
        "subtitle": "Kitchen, lighting and comfort for the home",
        "search": "Search home products...",
        "hero": {"badge": "Home Upgrade", "title": "Live Better", "subtitle": "Everyday essentials, imported"},
        "chips": [
            {"key": "all", "label": "All", "icon": "Sparkles"},
            {"key": "kitchen", "label": "Kitchen", "icon": "ChefHat"},
            {"key": "lighting", "label": "Lighting", "icon": "Lightbulb"},
            {"key": "comfort", "label": "Comfort", "icon": "Sofa"},
        ],
        "products": [
            ("kitchen", "Electric Blender 1.5L", "Smoothies and soups", 39.99, "zambia", 49.99),
            ("kitchen", "Non-Stick Cookware Set", "Five-piece pan set", 64.99, "china", None),
            ("kitchen", "Electric Kettle 1.7L", "Fast-boil stainless kettle", 27.99, "zambia", None),
            ("kitchen", "Knife Block Set", "Eight-piece steel knives", 44.99, "china", 54.99),
            ("kitchen", "Food Storage Container Set", "Airtight 10-piece set", 24.99, "china", None),
            ("lighting", "LED Strip Lights 10m", "App-controlled RGB", 22.99, "china", 29.99),
            ("lighting", "Solar Garden Lights x8", "Dusk-to-dawn path lights", 34.99, "china", None),
            ("lighting", "Rechargeable Desk Lamp", "Dimmable with power bank", 29.99, "china", None),
            ("lighting", "Smart Ceiling Light", "Colour changing, app control", 49.99, "china", 62.99),
            ("comfort", "Memory Foam Pillow Pair", "Contour neck support", 34.99, "china", None),
            ("comfort", "Standing Fan 16 inch", "Three-speed oscillating", 44.99, "zambia", 54.99),
            ("comfort", "Electric Blanket Double", "Timer and heat settings", 39.99, "china", None),
            ("comfort", "Massage Gun Deep Tissue", "Six-head percussion", 59.99, "china", 74.99),
            ("comfort", "Air Humidifier Diffuser", "Essential oil diffuser", 24.99, "china", None),
        ],
    },
]
