# Generated by Django 5.2.15 on 2026-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notificationpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
