# Generated by Django 5.2.15 on 2026-07-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_address_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
