# Generated by Django 5.2.15 on 2026-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seed_store_staff_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force a password change the next time this account logs into the admin.'),
        ),
    ]
